DROP TABLE IF EXISTS EMPLOYEE;
 
CREATE TABLE EMPLOYEE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  location VARCHAR(250) DEFAULT NULL
);